# Generated by Django 5.2.7 on 2025-11-07 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationhistory',
            old_name='name',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='educationhistory',
            old_name='qualification',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
