# Generated by Django 5.2.7 on 2025-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_name_educationhistory_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_history_order',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_history_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
