# Generated by Django 5.2.7 on 2025-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('job_history', models.TextField()),
                ('education_history', models.TextField()),
            ],
        ),
    ]
